version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - pull_request.closed
          - pull_request.opened
          - push
    payload:
      maxRunTime: 3600
      image: node
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          git clone {{event.head.repo.url}} repo && cd repo && git config
          advice.detachedHead false && git checkout {{event.head.sha}} && npm
          install . && npm test
    metadata:
      name: Run tests for taskcluster-index in Taskcluster
      description: write a .taskcluster.yml  that runs the tests
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
allowPullRequests: public
